# Generated by Django 3.1.6 on 2021-02-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarra',
            name='madera',
            field=models.CharField(default='No informada', max_length=50),
        ),
    ]
